Fix for error when installing openidconnect
For me env_file[0] resulted in following:

  File "../LayersBox/layersbox", line 717, in create_databases
    with open(join(servicedir, service_name, env_file[0])) as infile:
IOError: [Errno 2] No such file or directory:
'./services/openidconnect/o'

I don’t know why there was env_file[0], but fix assumes that sometimes
it is a list or a tuple and env_file[0] is needed.